services:
  mysql:
    image: mysql:8.2
    container_name: mysqlapp
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "${DB_PORT}:3306"
    networks:
      - backend_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8082:80"
    depends_on:
      - mysql
    networks:
      - backend_network

  node-server:
    build: .
    container_name: node-server
    ports:
     - "4000:4000"
    depends_on:
      - mysql
    networks:
      - backend_network

volumes:
  mysql_data:

networks:
  backend_network: