networks:
  backend_network:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
     
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - backend
      - frontend
      - mysql
      - phpmyadmin
    networks:
      - backend_network

  mysql:
    image: mysql:8.2
    container_name: MySQL-8.2
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: frauLaska
    volumes:
      - mysql_data:/var/lib/mysql
      - ./data/frauLaska.sql:/docker-entrypoint-initdb.d/frauLaska.sql   
    networks:
      - backend_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: MySQL-8.2
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ""  
    networks:
      - backend_network

  backend:
    image: backend
    container_name: backend    
    environment:
      DATABASE_HOST: MySQL-8.2
      DATABASE_USER: root
      DATABASE_PASSWORD: ""
      DATABASE_NAME: frauLaska
    networks:
      - backend_network

  frontend:
    image: frontend
    container_name: frontend   
    environment:
      - REACT_APP_API_URL=https://helthyfun.space/api/
    networks:
      - backend_network

volumes:
  mysql_data:
